@host = http://localhost:5286


GET {{host}}/api/products
tenant: CompanyWelDb

###

GET {{host}}/api/products/1
tenant: CompanyWelDb

###

POST {{host}}/api/products
tenant: CompanyWelDb
Content-Type: application/json

{
  "name": "Teclado HyperX RGB",
  "description": "Teclado mecânico com cores RGB",
  "rate": 5
}

###